version: '3'

services:
  railway_pricing:
    image: railway_pricing:latest
    container_name: railway_pricing
    privileged: true
    ports:
      - 8080:8080
    depends_on:
      - catalogue-db

  catalogue-db:
    image: postgres:13.4
    container_name: catalogue-db
    privileged: true
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/init:/docker-entrypoint-initdb.d
